<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-EventPipeline.Worker-14d3403d-3ac0-47ee-8153-7260324e2d5e</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClickHouse.Client" Version="7.4.1" />
    <PackageReference Include="Confluent.Kafka" Version="2.6.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EventPipeline.Data\EventPipeline.Data.csproj" />
  </ItemGroup>
</Project>
